### ISSUE TITLE
为什么没有系统监控画面

### ISSUE THREAD

**Issue by buster2004** [wxiaoqi/ace-admin#5]
直接下载执行的话，为什么没有系统监控画面啊

**Comment by wxiaoqi** [comment]
贴一下菜单地址，我看看

**Comment by buster2004** [comment]
现在我直接下来的项目，这是我本地的

这是sample的


我的db是
直接执行的
运行数据库脚本：依次运行数据库：ace-admin/db/init.sql



buster2004@163.com
 
发件人： Mr.AG
发送时间： 2017-08-15 14:42
收件人： wxiaoqi/ace-admin
抄送： buster2004; Author
主题： Re: [wxiaoqi/ace-admin] 为什么没有系统监控画面 (#5)
贴一下菜单地址，我看看

**Comment by buster2004** [comment]
是没有网关管理画面！

**Comment by wxiaoqi** [comment]
网关管理这块已经迁移至ace-gate了

**Comment by buster2004** [comment]
- -! 好吧，谢谢！



buster2004@163.com
 
发件人： Mr.AG
发送时间： 2017-08-15 17:06
收件人： wxiaoqi/ace-admin
抄送： buster2004; Author
主题： Re: [wxiaoqi/ace-admin] 为什么没有系统监控画面 (#5)
网关管理这块已经迁移至ace-gate了

**Comment by buster2004** [comment]
反应这么快 太感谢了
